name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Composer install
        uses: php-actions/composer@v6

      - name: PHPUnit
        uses: php-actions/phpunit@v3

      - name: PHPStan
        uses: php-actions/phpstan@v3
        with:
          path: src/

      - name: PHP Code Sniffer
        uses: php-actions/phpcs@v1
        with:
          php_version: 8.1
          path: src/
          standard: phpcs.xml.dist
